# Generated by Django 5.2.17 on 2026-09-01 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("booking", "0003_walkin_schedule_party_size_staff_is_on_roster_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PostDraft",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="対象日")),
                ("body", models.TextField(verbose_name="本文")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="sns/", verbose_name="画像"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "下書き(承認待ち)"),
                            ("approved", "承認済み"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="状態",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="承認時刻"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="承認者",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_drafts",
                        to="booking.store",
                        verbose_name="店舗",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PostResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(max_length=20, verbose_name="プラットフォーム"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("posted", "投稿済み"),
                            ("failed", "失敗"),
                            ("manual", "手動投稿してください"),
                        ],
                        max_length=10,
                        verbose_name="状態",
                    ),
                ),
                ("external_url", models.URLField(blank=True, verbose_name="投稿URL")),
                (
                    "detail",
                    models.CharField(blank=True, max_length=255, verbose_name="詳細"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="日時"),
                ),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="sns.postdraft",
                        verbose_name="下書き",
                    ),
                ),
            ],
            options={
                "ordering": ["platform", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PostTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="開店告知", max_length=50, verbose_name="テンプレート名"
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        default="【{store_name}】{date} 本日オープン!\n{casts_section}{arrivals_section}ご来店お待ちしております!",
                        verbose_name="本文テンプレート",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_templates",
                        to="booking.store",
                        verbose_name="店舗",
                    ),
                ),
            ],
        ),
    ]
