# Generated by Django 5.2.17 on 2026-09-01 06:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_store_store_valid_business_hours_and_more"),
        ("sns", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="postdraft",
            constraint=models.UniqueConstraint(
                fields=("store", "date"), name="unique_post_draft_per_day"
            ),
        ),
    ]
