# Generated by Django 5.2.17 on 2026-09-01 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("booking", "0003_walkin_schedule_party_size_staff_is_on_roster_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日付")),
                ("start_time", models.TimeField(verbose_name="開始")),
                ("end_time", models.TimeField(verbose_name="終了")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "予定"),
                            ("confirmed", "確定"),
                            ("absent", "欠勤"),
                        ],
                        default="planned",
                        max_length=10,
                        verbose_name="状態",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="メモ"),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="booking.staff",
                        verbose_name="スタッフ",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start_time"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("staff", "date", "start_time"), name="unique_shift"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TimeRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日付")),
                (
                    "clock_in",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="出勤打刻"
                    ),
                ),
                (
                    "clock_out",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="退勤打刻"
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_records",
                        to="booking.staff",
                        verbose_name="スタッフ",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("staff", "date"), name="unique_time_record_per_day"
                    )
                ],
            },
        ),
    ]
