# Generated by Django 5.2.17 on 2026-09-01 03:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("booking", "0003_walkin_schedule_party_size_staff_is_on_roster_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="品名")),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="カテゴリ"
                    ),
                ),
                (
                    "unit",
                    models.CharField(default="個", max_length=20, verbose_name="単位"),
                ),
                (
                    "reorder_point",
                    models.PositiveIntegerField(default=0, verbose_name="発注点"),
                ),
                (
                    "order_lot",
                    models.PositiveIntegerField(default=1, verbose_name="発注ロット"),
                ),
                (
                    "sns_announce",
                    models.BooleanField(default=False, verbose_name="SNS告知対象"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="取扱中")),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="booking.store",
                        verbose_name="店舗",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "発注案(承認待ち)"),
                            ("sent", "発注済み"),
                            ("cancelled", "取消"),
                        ],
                        default="proposed",
                        max_length=10,
                        verbose_name="状態",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="送信時刻"
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="メモ"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="承認者",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_orders",
                        to="booking.store",
                        verbose_name="店舗",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="数量")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.purchaseorder",
                        verbose_name="発注",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                        verbose_name="商品",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("arrival", "入荷"),
                            ("sale", "販売・消費"),
                            ("waste", "廃棄"),
                            ("adjust", "棚卸補正"),
                        ],
                        max_length=10,
                        verbose_name="種別",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(verbose_name="数量(入荷は正、消費は負)"),
                ),
                (
                    "at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="日時"
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="メモ"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="記録者",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="inventory.product",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "ordering": ["-at"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="仕入先名")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="発注先メール"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="メモ(電話番号・FAX等)"
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suppliers",
                        to="booking.store",
                        verbose_name="店舗",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_orders",
                to="inventory.supplier",
                verbose_name="仕入先",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="inventory.supplier",
                verbose_name="仕入先",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("store", "name"), name="unique_product_per_store"
            ),
        ),
    ]
