# Generated by Django 5.2.17 on 2026-09-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("proposed", "発注案(承認待ち)"),
                    ("sent", "発注済み(入荷待ち)"),
                    ("received", "入荷済み"),
                    ("cancelled", "取消"),
                ],
                default="proposed",
                max_length=10,
                verbose_name="状態",
            ),
        ),
    ]
