# Generated by Django 5.2.17 on 2026-09-01 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="closing_hour",
            field=models.PositiveSmallIntegerField(
                default=18, verbose_name="閉店時刻(時)"
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="opening_hour",
            field=models.PositiveSmallIntegerField(
                default=9, verbose_name="開店時刻(時)"
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.staff",
                verbose_name="占いスタッフ",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedule",
            constraint=models.UniqueConstraint(
                fields=("staff", "start"), name="unique_schedule_per_staff_start"
            ),
        ),
    ]
