# Generated by Django 5.2.17 on 2026-09-01 03:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_store_closing_hour_store_opening_hour_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WalkIn",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "party_size",
                    models.PositiveSmallIntegerField(default=1, verbose_name="人数"),
                ),
                (
                    "seated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="着席時刻"
                    ),
                ),
                (
                    "left_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="離席時刻"
                    ),
                ),
            ],
            options={
                "ordering": ["-seated_at"],
            },
        ),
        migrations.AddField(
            model_name="schedule",
            name="party_size",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="人数"),
        ),
        migrations.AddField(
            model_name="staff",
            name="is_on_roster",
            field=models.BooleanField(default=True, verbose_name="在籍中"),
        ),
        migrations.AddField(
            model_name="staff",
            name="kind",
            field=models.CharField(
                choices=[("staff", "スタッフ"), ("cast", "キャスト")],
                default="staff",
                max_length=10,
                verbose_name="区分",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="profile_image",
            field=models.ImageField(
                blank=True, upload_to="staff/", verbose_name="プロフィール画像"
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="sns_publishable",
            field=models.BooleanField(default=False, verbose_name="SNS掲載可"),
        ),
        migrations.AddField(
            model_name="store",
            name="business_type",
            field=models.CharField(
                choices=[
                    ("fortune", "占い(スタッフ指名・時間枠)"),
                    ("restaurant", "飲食(座席・人数)"),
                ],
                default="fortune",
                max_length=20,
                verbose_name="業態",
            ),
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="座席名")),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(default=2, verbose_name="定員"),
                ),
                (
                    "seat_type",
                    models.CharField(
                        choices=[
                            ("counter", "カウンター"),
                            ("table", "テーブル"),
                            ("private", "個室"),
                            ("fortune", "鑑定席"),
                        ],
                        default="table",
                        max_length=10,
                        verbose_name="種別",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="使用中")),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="booking.store",
                        verbose_name="店舗",
                    ),
                ),
            ],
            options={
                "ordering": ["store", "name"],
            },
        ),
        migrations.AddField(
            model_name="schedule",
            name="seat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schedules",
                to="booking.seat",
                verbose_name="座席",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("seat__isnull", False)),
                fields=("seat", "start"),
                name="unique_schedule_per_seat_start",
            ),
        ),
        migrations.AddField(
            model_name="walkin",
            name="seat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="walkins",
                to="booking.seat",
                verbose_name="座席",
            ),
        ),
        migrations.AddConstraint(
            model_name="seat",
            constraint=models.UniqueConstraint(
                fields=("store", "name"), name="unique_seat_name_per_store"
            ),
        ),
    ]
