# Generated by Django 5.2.17 on 2026-09-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_walkin_schedule_party_size_staff_is_on_roster_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="store",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("closing_hour__lte", 24),
                    ("opening_hour__lt", models.F("closing_hour")),
                ),
                name="store_valid_business_hours",
            ),
        ),
        migrations.AddConstraint(
            model_name="walkin",
            constraint=models.UniqueConstraint(
                condition=models.Q(("left_at__isnull", True)),
                fields=("seat",),
                name="unique_active_walkin_per_seat",
            ),
        ),
    ]
