# Generated by Django 5.2.17 on 2026-09-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_store_store_valid_business_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="is_manager",
            field=models.BooleanField(default=False, verbose_name="店長(承認権限)"),
        ),
    ]
