# Generated by Django 5.2.17 on 2026-09-01 08:31

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_staff_is_manager"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="store",
            name="store_valid_business_hours",
        ),
        migrations.AddConstraint(
            model_name="store",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("closing_hour__lte", 30),
                    ("opening_hour__lt", models.F("closing_hour")),
                    ("opening_hour__lte", 23),
                    (
                        "closing_hour__lte",
                        django.db.models.expressions.CombinedExpression(
                            models.F("opening_hour"), "+", models.Value(24)
                        ),
                    ),
                ),
                name="store_valid_business_hours",
            ),
        ),
    ]
