# Generated by Django 5.2.17 on 2026-09-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0006_remove_store_store_valid_business_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="enable_gbp",
            field=models.BooleanField(
                default=True, verbose_name="Googleマップ(GBP)連携"
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="enable_inventory",
            field=models.BooleanField(default=True, verbose_name="在庫・発注機能"),
        ),
        migrations.AddField(
            model_name="store",
            name="enable_seat_board",
            field=models.BooleanField(default=True, verbose_name="座席ボード"),
        ),
        migrations.AddField(
            model_name="store",
            name="enable_sns",
            field=models.BooleanField(default=True, verbose_name="SNS投稿機能"),
        ),
    ]
