# Generated by Django 5.2.17 on 2026-09-01 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0007_store_enable_gbp_store_enable_inventory_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="schedule",
            name="unique_schedule_per_staff_start",
        ),
        migrations.AddField(
            model_name="schedule",
            name="cancel_token",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                unique=True,
                verbose_name="取消トークン",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="登録日時"
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="customer_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="連絡先メール"
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="customer_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="連絡先電話"
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="enable_web_reservation",
            field=models.BooleanField(default=True, verbose_name="Web座席予約(飲食)"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.staff",
                verbose_name="占いスタッフ",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("staff__isnull", False)),
                fields=("staff", "start"),
                name="unique_schedule_per_staff_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("staff__isnull", False), ("seat__isnull", False), _connector="OR"
                ),
                name="schedule_has_staff_or_seat",
            ),
        ),
    ]
