"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 2.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# 本番では必ず環境変数 DJANGO_SECRET_KEY を設定すること。
# 旧リポジトリにコミットされていたキーは漏洩済みとして扱い、使用しない。
_DEV_SECRET_KEY = 'django-insecure-dev-only-key-do-not-use-in-production'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', _DEV_SECRET_KEY)

DEBUG = os.environ.get('DJANGO_DEBUG', 'true').lower() in ('1', 'true', 'yes')

if not DEBUG and SECRET_KEY == _DEV_SECRET_KEY:
    # 本番でシークレット未設定のまま起動しない(フェイルセーフ)。
    # 開発用キーは公開リポジトリに載っており、セッション偽造が可能になるため。
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured('DJANGO_DEBUG=false のときは DJANGO_SECRET_KEY の設定が必須です。')

ALLOWED_HOSTS = [h for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h]
if not ALLOWED_HOSTS and DEBUG:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Cloud Run 等のリバースプロキシ配下で HTTPS 判定するための設定
CSRF_TRUSTED_ORIGINS = [o for o in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if o]

if not DEBUG:
    # 本番のHTTPS強制(check --deploy の W004/W008/W012/W016 対応)。
    # Cloud Run はプロキシ終端のため X-Forwarded-Proto で判定する。
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = os.environ.get('DJANGO_SECURE_SSL_REDIRECT', 'true').lower() == 'true'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # HSTS は控えめな初期値(1時間)。HTTPS のみで安定運用できたら env で延ばす。
    # includeSubDomains / preload(check --deploy W020/W021)は解除がほぼ効かないため
    # 独自ドメイン運用が固まるまで意図的に有効化しない。
    SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_HSTS_SECONDS', '3600'))


# Application definition

INSTALLED_APPS = [
    'booking.apps.BookingConfig',
    'attendance.apps.AttendanceConfig',
    'operations.apps.OperationsConfig',
    'sns.apps.SnsConfig',
    'inventory.apps.InventoryConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# 本番は DATABASE_URL(PostgreSQL / Cloud SQL)を設定する。
# Cloud Run はコンテナ再作成でローカルファイルが消えるため、SQLite は開発専用。
if os.environ.get('DATABASE_URL'):
    from .database import database_config_from_url
    DATABASES = {'default': database_config_from_url(os.environ['DATABASE_URL'])}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.environ.get('DJANGO_MEDIA_ROOT', os.path.join(BASE_DIR, 'media'))

# メール(発注書送信に使用)。本番はSMTP設定を環境変数で与える。
EMAIL_BACKEND = os.environ.get(
    'DJANGO_EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend'
)
EMAIL_HOST = os.environ.get('DJANGO_EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('DJANGO_EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('DJANGO_EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('DJANGO_EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('DJANGO_EMAIL_USE_TLS', 'true').lower() == 'true'
DEFAULT_FROM_EMAIL = os.environ.get('DJANGO_DEFAULT_FROM_EMAIL', 'noreply@example.com')


import datetime

import jpholiday

# 日本の祝日(前年〜翌年)。ハードコードだと毎年メンテが必要になるため jpholiday で生成する。
_this_year = datetime.date.today().year
PUBLIC_HOLIDAYS = [
    d
    for year in range(_this_year - 1, _this_year + 2)
    for d, _name in jpholiday.year_holidays(year)
]
LOGIN_URL = 'booking:login'
LOGIN_REDIRECT_URL = 'booking:store_list'
LOGOUT_REDIRECT_URL = 'booking:login'

DEFAULT_AUTO_FIELD='django.db.models.AutoField'

# エラートラッキング(任意)。SENTRY_DSN を設定すると有効になる。
SENTRY_DSN = os.environ.get('SENTRY_DSN', '')
if SENTRY_DSN:
    import sentry_sdk
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        environment=os.environ.get('SENTRY_ENVIRONMENT', 'production' if not DEBUG else 'development'),
        send_default_pii=False,  # 予約者名・キャスト名等の個人情報は送らない
        traces_sample_rate=float(os.environ.get('SENTRY_TRACES_SAMPLE_RATE', '0')),
    )
