# Generated by Django 5.2.17 on 2026-09-01 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("booking", "0003_walkin_schedule_party_size_staff_is_on_roster_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessDay",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日付")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preparing", "準備中"),
                            ("open", "営業中"),
                            ("closed", "閉店"),
                        ],
                        default="preparing",
                        max_length=10,
                        verbose_name="状態",
                    ),
                ),
                (
                    "opening_hour_override",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="臨時開店時刻(時)"
                    ),
                ),
                (
                    "closing_hour_override",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="臨時閉店時刻(時)"
                    ),
                ),
                (
                    "opened_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="開店時刻"
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="閉店時刻"
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="メモ"),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_days",
                        to="booking.store",
                        verbose_name="店舗",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="タスク名")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="表示順"),
                ),
                ("is_done", models.BooleanField(default=False, verbose_name="完了")),
                (
                    "done_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完了時刻"
                    ),
                ),
                (
                    "alert",
                    models.CharField(blank=True, max_length=255, verbose_name="警告"),
                ),
                (
                    "business_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="operations.businessday",
                        verbose_name="営業日",
                    ),
                ),
                (
                    "done_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="完了者",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistTemplateItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="タスク名")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="表示順"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_template",
                        to="booking.store",
                        verbose_name="店舗",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="businessday",
            constraint=models.UniqueConstraint(
                fields=("store", "date"), name="unique_business_day"
            ),
        ),
    ]
